[book]
authors = ["phoenixr-codes"]
language = "en"
multilingual = false
src = "src"
title = "mdbook-webinclude test book"
description = "A demo book to test and validate changes"

[preprocessor.webinclude]
